#!/bin/bash

LOCAL=`cd $(dirname "$0"); pwd`
BT_SERVICE_NAME="GlassController"
BT_HANDLE="0x12000"
BT_CHANNEL=`sdptool browse local | grep "Channel:" | 
sort | awk 'BEGIN {c = 0; found = 0 } { ++ c; if (c != $2) { found = 1; exit } } END { if (found) print c; else print (c + 1) }'`

[ ${BT_CHANNEL} -gt 32 ] && { echo "no channel to use"; exit 1; }
sdptool add --channel=${BT_CHANNEL} --handle=${BT_HANDLE} sp
sdptool setattr ${BT_HANDLE} 0x0100 ${BT_SERVICE_NAME}
sudo rfcomm -r listen gc ${BT_CHANNEL} \
    sudo -u "#$UID" env \
    DBUS_SESSION_BUS_ADDRESS=$DBUS_SESSION_BUS_ADDRESS \
    DBUS_SESSION_BUS_PID=$DBUS_SESSION_BUS_PID \
    GC_DEBUG=$GC_DEBUG $LOCAL/process_conn '{}'
sdptool del ${BT_HANDLE}
